// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/bug/ent/predicate"
	"entgo.io/bug/ent/userfoo"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserFooDelete is the builder for deleting a UserFoo entity.
type UserFooDelete struct {
	config
	hooks    []Hook
	mutation *UserFooMutation
}

// Where appends a list predicates to the UserFooDelete builder.
func (ufd *UserFooDelete) Where(ps ...predicate.UserFoo) *UserFooDelete {
	ufd.mutation.Where(ps...)
	return ufd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ufd *UserFooDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ufd.hooks) == 0 {
		affected, err = ufd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserFooMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ufd.mutation = mutation
			affected, err = ufd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ufd.hooks) - 1; i >= 0; i-- {
			if ufd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ufd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ufd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ufd *UserFooDelete) ExecX(ctx context.Context) int {
	n, err := ufd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ufd *UserFooDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: userfoo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userfoo.FieldID,
			},
		},
	}
	if ps := ufd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ufd.driver, _spec)
}

// UserFooDeleteOne is the builder for deleting a single UserFoo entity.
type UserFooDeleteOne struct {
	ufd *UserFooDelete
}

// Exec executes the deletion query.
func (ufdo *UserFooDeleteOne) Exec(ctx context.Context) error {
	n, err := ufdo.ufd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userfoo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ufdo *UserFooDeleteOne) ExecX(ctx context.Context) {
	ufdo.ufd.ExecX(ctx)
}
